postgres:
  image: postgres:9.4.5
  environment:
    POSTGRES_USER: crashatmypad
    POSTGRES_PASSWORD: padmypad
  ports:
    - '5432:5432'
  volumes:
    - ~/.docker-volumes/crashatmypad/postgresql/data:/var/lib/postgresql/data

redis:
  image: redis:2.8.22
  ports:
    - '6379:6379'
  volumes:
    - ~/.docker-volumes/crashatmypad/redis/data:/var/lib/redis/data

crashatmypad:
  build: .
  command: gunicorn -b 0.0.0.0:8000 --reload --access-logfile - "crashatmypad.app:create_app()"
  environment:
    PYTHONUNBUFFERED: true
  links:
    - postgres
    - redis
#  volumes:
#    - .:/crashatmypad
  ports:
    - '8000:8000'
